species_names:
  - Homo_sapiens
  - Bos_taurus
  - Danio_rerio
  - Canis_lupus_familiaris
  - Gallus_gallus
  - Gorilla_gorilla_gorilla
  - Lepisosteus_oculatus
  - Monodelphis_domestica
  - Mus_musculus
  - Oryzias_latipes
  - Pan_troglodytes
  - Rattus_norvegicus
  - Xenopus_tropicalis
