# config file for simulating reads from Human Ensembl Data

reference_files:
  Hsapiens_ensembl:
    fasta: "/Users/tessa/dib-lab/simulate_reads/Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa"
    gff: "/Users/tessa/dib-lab/simulate_reads/Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf"

attributes:
  gene_name:
    - GNAS
    - AGER
    - CDKN2A 
    - CSF2RA
    - GNRHR
    - XBP1

# add flank # base pairs upstream and downstream of gene
flank_bp: 50
slop_bp: 50

simulation_params:
  read_len: 150
  paired: False
  num_rep: 5
  num_reads_per_transcript: 1000
