# config file for simulating reads from Human Ensembl Data

# NOTE:first,  manually prepocessed genes.gtf --> chromosomes.gff3 b/c genome.fa only contains chromosome fastas, can't extract patches/unassigned/etc
# chormosomes.gff3 generated in R, like so:
    # library(rtracklayer)
    # h_gtf <- import("Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf")
    # seqnames_to_keep = c(1:22, "M", "X", "Y") # keep only seqs assigned to chromosomes
    # filtered <- subset(h_gtf, seqnames  %in% seqnames_to_keep) # filter all the extra/unassigned/patches/etc entries from the gff file.
    # export(filtered, "chromosomes.gff3")

reference_files:
  Hsapiens_ensembl:
    fasta: "Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa"
    genome_info: "Homo_sapiens/Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa.fai"
    gff: "chromosomes.gff3" 
    #gff: "Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf"

attributes:
  #atm only gene_name enabled, modify filter_gff.R to enable additional attributes
  gene_name:
    - GNAS
    - AGER
    - CDKN2A 
    - CSF2RA
    - GNRHR
    - XBP1

# flank or slop # base pairs upstream and downstream of gene.
flank_bp: 50 # excludes feature itself (just surrounding bp)
slop_bp: 50 # includes feature itself

# parameters for polyester read simulation
# used by simulate_reads.R
simulation_params:
  read_len: 150
  paired: False
  num_rep: 5
  num_reads_per_transcript: 1000
