# config file for simulating reads from Human Ensembl Data

# NOTE:first,  manually prepocessed genes.gtf --> chromosomes.gff3 b/c genome.fa only contains chromosome fastas, can't extract patches/unassigned/etc
# chormosomes.gff3 generated in R, like so:
    # library(rtracklayer)
    # h_gtf <- import("Homo_sapiens/Ensembl/GRCh37/Annotation/Genes/genes.gtf")
    # seqnames_to_keep = c(1:22, "M", "X", "Y") # keep only seqs assigned to chromosomes
    # filtered <- subset(h_gtf, seqnames  %in% seqnames_to_keep) # filter all the extra/unassigned/patches/etc entries from the gff file.
    # export(filtered, "chromosomes.gff3")

reference_files:
  Homo_sapiens_Ensembl_GRCh37:
    # use annotated gene sets from igenomes http://ccb.jhu.edu/software/tophat/igenomes.shtml
    database_url: "ftp://igenome:G3nom3s4u@ussd-ftp.illumina.com/Homo_sapiens/Ensembl/GRCh37/Homo_sapiens_Ensembl_GRCh37.tar.gz"
    database_fileformat: "tar.gz" #tar.gz and .gz are valid fileformats
    #database: "Homo_sapiens_Ensembl_GRCh37"
    # relative paths to files within the database
    fasta: "Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa"
    #gff: "Ensembl/GRCh37/Annotation/Genes/genes.gtf"
    genome_info: "Ensembl/GRCh37/Sequence/WholeGenomeFasta/genome.fa.fai"
    gff: "chromosomes.gff3"

attributes:
  #full_genome: False
  #atm only gene_name enabled, modify filter_gff.R to enable additional attributes
  gene_name:
    - GNAS
    - AGER
    - CDKN2A 
    - CSF2RA
    - GNRHR
    - XBP1

# flank or slop # base pairs upstream and downstream of gene.
flank_bp: 50 # excludes feature itself (just surrounding bp)
slop_bp: 50 # includes feature itself

# parameters for polyester read simulation
# used by simulate_reads.R
simulation_params:
  read_len: 150
  paired: False
  num_replicates: 5
  num_reads_per_transcript: 1000
