#samples_csv: gene_test.csv
#samples_csv: QfO_vertebrate_samples.csv
# just human:
samples_csv: QfO_vertebrates/simulate_reads/Hsapiens_samples.qfo_ncRNA.csv 
# run full:
#samples_csv: QfO_vertebrates/simulate_reads/QfO_vertebrates_samples.qfo_ncRNA.csv

out_dir: output_simreads/sencha

sencha_params:
  peptide_references:
    sprot: 
      path: /home/ntpierce/2020-pep/khtools_testing/uniprot_sprot.fasta.gz
      tablesize: 1e9
      index_memory: 20000
    Hsapiens_QfO: 
      path: /home/ntpierce/2020-simulate-rnaseq/output_simreads/data/QfO_release_2018_04/Eukaryota/UP000005640_9606.fasta
      tablesize: 1e8
      #tablesize: 1e9
      index_memory: 20000
    #merc: 
    #  path: /home/ntpierce/2020-pep/khtools_testing/MERC.fasta.gz
    #  tablesize: 1e10
    #  index_memory: 60000
  alphabet:
    protein:
      ksizes:
        - 5
        - 7
        - 9
        - 10
      jaccard_threshold:
        #- 0.45
        - 0.5
        #- 0.55
        #- 0.6
    dayhoff:
      ksizes:
        - 9
        - 11
        - 13
        - 15
      jaccard_threshold:
        #- 0.45
        - 0.5
        #- 0.55
        #- 0.6
    hp:
      ksizes:
        - 15
        - 17
        - 19
        - 21
      jaccard_threshold:
        #- 0.75
        - 0.8
        #- 0.85
        #- 0.9
